# This is a config file for using test kitchen with docker.
# Install the ChefDK: https://downloads.chef.io/chef-dk/
# run `chef gem install kitchen-docker`
# then run `kitchen converge` to spin a docker container
# and test your cookbook.
---
driver:
  name: docker

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[rails-server-starter-pack::default]
    attributes:
